name: deployment_strategy
description: "Sets variables depending on certain states"
inputs:
  deploy_prod:
    description: "Deployment to centriufge.io?"
    required: true
    default: 'false'

outputs:
  function_name: 
    description: "URL to deploy your front-end"
    value: ${{ steps.setenv.outputs.functions_name}}    
  bucket_url: 
    description: "URL to deploy your front-end"
    value: ${{ steps.setenv.outputs.bucket_url}}
  env_name:
    description: "Environment name for reference"
    value: ${{ steps.setenv.outputs.env_name }}

runs:
  using: composite
  steps: 
    - id: setenv
      shell: bash
      env: 
       # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
       ref: ${{ github.head_ref || github.ref_name }}
       pr_number: ${{ github.event.number }}
      # Set Alatair and Centrifuge to deploy in the prod Gcloud account
      # both will require approval to use the GCE prod secrets
      run: |
        echo "Set env vars for deployment"

        echo "max_instances=2" >> $GITHUB_OUTPUT

        if  ${{ github.ref == 'refs/heads/main' }} ; then
          if  ${{ inputs.deploy_prod == 'true' }}; then
            #  PROD
            echo "bucket_url=www.centrifuge.io" >> $GITHUB_OUTPUT
            echo "functions_name=webapi-main" >> $GITHUB_OUTPUT
            echo "env_name=production" >> $GITHUB_OUTPUT
            echo "max_instances=10" >> $GITHUB_OUTPUT
            
          else
            #  STAGING
            echo "bucket_url=website-staging.k-f.dev" >> $GITHUB_OUTPUT
            echo "functions_name=webapi-main" >> $GITHUB_OUTPUT
            echo "env_name=staging" >> $GITHUB_OUTPUT            
            
          fi
        elif ${{ github.event_name == 'pull_request' }}; then
          # PRs
            echo "bucket_url=preview-pr${{ env.pr_number }}.k-f.dev" >> $GITHUB_OUTPUT
            echo "functions_name=webapi-${{ env.ref }}" >> $GITHUB_OUTPUT
            echo "env_name=pr" >> $GITHUB_OUTPUT
        else
          echo "::error title=No env to deploy::Workflow called from non-deployable branch/tag"
          exit 1
        fi   