name: Discover function URL
description: "Discover the URL given a function's name"
inputs:
  GWIP:
    required: true
    description: Github Workload ID
  GSA:
    required: true
    description: Github Servicer Account
outputs:
  function_url:
    description: "the discovered URL"
    value: ${{ steps.discover.outputs.url }} 
runs:
  using: composite
  steps:
    ############################################################################################
    # Second look up the function's URL
    # Warning: A Google Cloud token is created here, handle with care
    ############################################################################################
    - name: Auth gcloud
      id: gauth
      uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # @v1
      with:
        workload_identity_provider: '${{ secrets.GWIP }}'
        service_account: '${{ secrets.GSA }}'

    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@d51b5346f85640ec2aa2fa057354d2b82c2fcbce # v1.0.1

    - name: Discover function URL
      shell: bash
      id: discover
      # max_retry and sleep will consume GHA minutes. It shuold only fail when a PR is still to be deployed though
      # Initial value: 6 * 60(sleep)
      run: |
        echo "Called from website job, keep searching for function"
        max_retry=7
        counter=0
        while ! gcloud functions describe --region ${{ vars.GCP_REGION }} ${{ steps.deploy_vars.outputs.function_name }} 1> /dev/null && 
                [ ${counter} -lt ${max_retry} ]
        do
          echo " Function not found - Try #${counter}"
          echo "Wait 1 min..."
          # Try once every minute
          sleep 60
          echo "Trying again:"
          counter=$((counter+1))
          
        done
        if ! gcloud functions describe --region ${{ vars.GCP_REGION }} ${{ steps.deploy_vars.outputs.function_name }} &> /dev/null; then
          echo "::error title=Not_found::Function ${{ steps.deploy_vars.outputs.function_name }} not found, check functions deploy and re-run this job"
          exit 1
        else
          echo "url=$(gcloud functions describe --region ${{ vars.GCP_REGION }} ${{ steps.deploy_vars.outputs.function_name }} --format='value(httpsTrigger.url)')" >> $GITHUB_OUTPUT
        fi
