export const links = {
  twitter: 'https://twitter.com/centrifuge',
  telegram: 'https://t.me/centrifuge_chat',
  medium: 'https://medium.com/centrifuge',
  blog: 'https://centrifuge.mirror.xyz',
  discord: 'https://discord.com/invite/yEzyUq5gxF',
  youtube: 'https://www.youtube.com/channel/UCfNkoq7YLrr8MeSJ3a6jVcA',
  github: 'https://github.com/centrifuge/',
  linkedin: 'https://www.linkedin.com/company/centrifugehq/',
  docs: 'https://docs.centrifuge.io/',
  app: 'https://app.centrifuge.io/',
  audits: 'https://github.com/centrifuge/security/tree/main/audits',
  forum: 'https://gov.centrifuge.io/',
  prime: 'https://forms.gle/kt1GShLcWapMGzjs7',
  primeBlogPost: 'https://centrifuge.mirror.xyz/KyrMWLKMccFCNfSlvjxe7uyhba7oLrUzlBuZ7GQTn6s',
  fundManagement: 'https://example.com/fund-management',
  fundManagementBlogPost: 'https://centrifuge.mirror.xyz/pn5NlZ5UY5pdtOy_FFZ1cNWr0Dn1QBk2yCeJ6ZXQQoc',
  podcast: 'https://open.spotify.com/show/3mcy2eIFO9qUFlxhZeYMV4',
  announcements: 'https://fixing.finance',
  bis: 'https://www.bis.org/publ/work1116.htm',
  hkma: 'https://www.hkma.gov.hk/media/eng/publication-and-research/research/research-memorandums/2023/RM04-2023.pdf'
}
