export const links = {
  announcements: 'https://fixing.finance',
  app: 'https://app.centrifuge.io/',
  audits: 'https://github.com/centrifuge/security/tree/main/audits',
  bis: 'https://www.bis.org/publ/work1116.htm',
  blog: 'https://centrifuge.mirror.xyz',
  discord: 'https://discord.com/invite/yEzyUq5gxF',
  docs: 'https://docs.centrifuge.io/',
  forum: 'https://gov.centrifuge.io/',
  fundManagement: 'https://www.coindesk.com/business/2024/08/27/tokenization-pioneer-centrifuge-unveils-lending-market-with-morpho-coinbase/',
  fundManagementBlogPost: 'https://centrifuge.mirror.xyz/pn5NlZ5UY5pdtOy_FFZ1cNWr0Dn1QBk2yCeJ6ZXQQoc',
  github: 'https://github.com/centrifuge/',
  hkma: 'https://www.hkma.gov.hk/media/eng/publication-and-research/research/research-memorandums/2023/RM04-2023.pdf',
  linkedin: 'https://www.linkedin.com/company/centrifugehq/',
  medium: 'https://medium.com/centrifuge',
  morpho: 'https://app.morpho.org/market?id=0x83262d91702f90d9edf6c737ceb46e59a2bcfc7ba856e1e8448b7824f83a07e3&network=base&morphoPrice=1.0',
  podcast: 'https://open.spotify.com/show/3mcy2eIFO9qUFlxhZeYMV4',
  prime: 'https://forms.gle/kt1GShLcWapMGzjs7',
  primeBlogPost: 'https://centrifuge.mirror.xyz/KyrMWLKMccFCNfSlvjxe7uyhba7oLrUzlBuZ7GQTn6s',
  telegram: 'https://t.me/centrifuge_chat',
  twitter: 'https://twitter.com/centrifuge',
  youtube: 'https://www.youtube.com/channel/UCfNkoq7YLrr8MeSJ3a6jVcA',
  rwasummit: 'https://www.rwasummit.io/'
}
