export const links = {
  twitter: 'https://twitter.com/centrifuge',
  telegram: 'https://t.me/centrifuge_chat',
  medium: 'https://medium.com/centrifuge',
  blog: 'https://centrifuge.mirror.xyz',
  discord: 'https://discord.com/invite/yEzyUq5gxF',
  youtube: 'https://www.youtube.com/channel/UCfNkoq7YLrr8MeSJ3a6jVcA',
  github: 'https://github.com/centrifuge/',
  linkedin: 'https://www.linkedin.com/company/centrifugehq/',
  docs: 'https://docs.centrifuge.io/',
  app: 'https://app.centrifuge.io/',
  audits: 'https://github.com/centrifuge/security/tree/main/audits',
  forum: 'https://gov.centrifuge.io/',
  prime: 'https://forms.gle/kt1GShLcWapMGzjs7',
  primeBlogPost: 'https://medium.com/centrifuge/introducing-centrifuge-prime-real-yields-real-defi-b97a0e767f18',
}
